#!/usr/bin/env python3
"""TIL README.md 자동 생성 스크립트.

til/ 디렉토리의 모든 .md 파일을 스캔하여
카테고리별 목차가 포함된 README.md를 생성한다.
GitHub Actions에서 push 시마다 자동 실행된다.
"""

import os
import re
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).parent.parent
IGNORE_DIRS = {
    ".git", ".github", "scripts", "reviews", "blog-drafts",
    "node_modules", "__pycache__"
}
IGNORE_FILES = {"README.md"}

CATEGORY_LABELS = {
    "nextjs": "Next.js",
    "react": "React",
    "typescript": "TypeScript",
    "python": "Python",
    "supabase": "Supabase",
    "ai": "AI / ML",
    "database": "Database",
    "docker": "Docker",
    "devops": "DevOps / CI-CD",
    "troubleshooting": "Troubleshooting",
    "architecture": "Architecture",
    "css-tailwind": "CSS / Tailwind",
    "git-github": "Git / GitHub",
    "general": "General",
}


def extract_title(filepath: Path) -> str:
    """마크다운 파일에서 첫 번째 # 제목을 추출한다."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("# "):
                    return line[2:].strip()
    except Exception:
        pass
    return filepath.stem.replace("-", " ").title()


def extract_date(filepath: Path) -> str:
    """파일 내에서 날짜를 추출하거나 수정 시간을 반환한다."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read(2000)
            match = re.search(r"\*\*날짜\*\*:\s*(\d{4}-\d{2}-\d{2})", content)
            if match:
                return match.group(1)
    except Exception:
        pass
    mtime = os.path.getmtime(filepath)
    return datetime.fromtimestamp(mtime).strftime("%Y-%m-%d")


def scan_entries() -> dict:
    """카테고리별 TIL 엔트리를 수집한다."""
    categories = {}

    for item in sorted(REPO_ROOT.iterdir()):
        if not item.is_dir() or item.name in IGNORE_DIRS or item.name.startswith("."):
            continue

        entries = []
        for md_file in sorted(item.glob("*.md")):
            if md_file.name in IGNORE_FILES:
                continue
            title = extract_title(md_file)
            date = extract_date(md_file)
            rel_path = md_file.relative_to(REPO_ROOT).as_posix()
            entries.append({"title": title, "date": date, "path": rel_path})

        if entries:
            categories[item.name] = entries

    return categories


def generate_readme(categories: dict) -> str:
    """README.md 내용을 생성한다."""
    total = sum(len(v) for v in categories.values())
    today = datetime.now().strftime("%Y-%m-%d")

    lines = [
        "# TIL (Today I Learned)",
        "",
        f"> 매일 배운 것을 기록합니다. ({total}개 항목)",
        "",
        f"[![GitHub last commit](https://img.shields.io/github/last-commit/Krocean/til)](https://github.com/Krocean/til)",
        "",
        "---",
        "",
    ]

    # 카테고리 요약
    lines.append("## Categories")
    lines.append("")
    for cat_dir in sorted(categories.keys()):
        label = CATEGORY_LABELS.get(cat_dir, cat_dir.replace("-", " ").title())
        count = len(categories[cat_dir])
        lines.append(f"- **[{label}](#{cat_dir})** ({count})")
    lines.append("")
    lines.append("---")
    lines.append("")

    # 카테고리별 목록
    for cat_dir in sorted(categories.keys()):
        label = CATEGORY_LABELS.get(cat_dir, cat_dir.replace("-", " ").title())
        entries = sorted(categories[cat_dir], key=lambda x: x["date"], reverse=True)
        lines.append(f"## {label}")
        lines.append(f"<a name=\"{cat_dir}\"></a>")
        lines.append("")
        for entry in entries:
            lines.append(f"- [{entry['title']}]({entry['path']}) — {entry['date']}")
        lines.append("")

    # 푸터
    lines.append("---")
    lines.append("")
    lines.append(f"*Last updated: {today} | Auto-generated by [generate-readme.py](scripts/generate-readme.py)*")
    lines.append("")

    return "\n".join(lines)


def main():
    categories = scan_entries()
    readme_content = generate_readme(categories)
    readme_path = REPO_ROOT / "README.md"
    readme_path.write_text(readme_content, encoding="utf-8")
    total = sum(len(v) for v in categories.values())
    print(f"README.md updated: {total} entries across {len(categories)} categories")


if __name__ == "__main__":
    main()
